// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo4ApDWa1kHANXAz9e5ojvJWs9nGQu1oQ',
    appId: '1:780853708258:web:369917ff8f7edf72e865bb',
    messagingSenderId: '357033720656',
    projectId: 'braided-tracker-343119',
    authDomain: 'right-car.firebaseapp.com',
    databaseURL: 'https://right-car-default-rtdb.firebaseio.com',
    storageBucket: 'right-car.appspot.com',
    measurementId: 'G-0RXNJ57YQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoYYsJqTV_lorOA2OdPhPYWt_X4LHrfgE',
    appId: '1:357033720656:android:1893d0b0e98dbe4c04ca55',
    messagingSenderId: '357033720656',
    projectId: 'braided-tracker-343119',
    databaseURL: 'https://braided-tracker-343119-default-rtdb.firebaseio.com',
    storageBucket: 'braided-tracker-343119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-l5lGKG2KaGh0T3RlFb4Zpwe3vPKTcww',
    appId: '1:780853708258:ios:8e56f4821e907a79e865bb',
    messagingSenderId: '780853708258',
    projectId: 'right-car',
    databaseURL: 'https://right-car-default-rtdb.firebaseio.com',
    storageBucket: 'right-car.appspot.com',
    androidClientId: '780853708258-89l5gfcmtc4odv37j8nrl7tgb3vjugt7.apps.googleusercontent.com',
    iosClientId: '780853708258-eg7349vs24di4mk4bmbrr9thc79cqr40.apps.googleusercontent.com',
    iosBundleId: 'bundle.id',
  );
}
